version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: citydynamics
      POSTGRES_USER: citydynamics
    volumes:
      - ./deploy/backup-db.sh:/backup-db.sh
      - ./deploy/backup:/backup
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
      - data-volume:/data

  api:
    build: .
    ports:
      - "8117:8001"
    links:
      - database:database
    environment:
      - DB_NAME=city-dynamics
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=citydynamics.wsgi:application

  importer:
    build: ./importer
    links:
      - database:database
    environment:
      PGPASSWORD: insecure
      # Following are secret, should be provided as environment variables.
      # E.g. by running in terminal
      # export STADSWERKEN_OBJECTSTORE_PASSWORD="mypassword"
      STADSWERKEN_OBJECTSTORE_PASSWORD:
    volumes:
      - data-volume:/data
      #- ~/data:/data


  analyzer:
    build: ./analyzer
    links:
      - database:database

  front:
    ports:
      - "8080:80"
    build: ./front
    #links:
    #  - api:api

volumes:
  data-volume: